name: Run Tests
on: [ push, pull_request ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Run tests
        run: yarn test
        env:
          IS_GITHUB: "yes"

      - name: Output lcov report
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage/lcov-report
          destination_dir: "coverage/${{ github.sha }}"
